### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by emukoya** [hamaadshah/autoencoders_pytorch#4]
Would you kindly mention the paper that was used with this code implementation, if any.

**Comment by hamaadshah** [comment]
Hi: You'll find the references in the Jupyter Notebook. 

References
Goodfellow, I., Bengio, Y. and Courville A. (2016). Deep Learning (MIT Press).
Geron, A. (2017). Hands-On Machine Learning with Scikit-Learn & Tensorflow (O'Reilly).
Kingma, D. P., and Welling M. (2014). Auto-Encoding Variational Bayes (https://arxiv.org/abs/1312.6114).
http://scikit-learn.org/stable/#
https://towardsdatascience.com/learning-rate-schedules-and-adaptive-learning-rate-methods-for-deep-learning-2c8f433990d1
https://stackoverflow.com/questions/42177658/how-to-switch-backend-with-keras-from-tensorflow-to-theano
https://blog.keras.io/building-autoencoders-in-keras.html
https://keras.io
https://www.cs.cornell.edu/courses/cs1114/2013sp/sections/S06_convolution.pdf
http://deeplearning.net/tutorial/lstm.html
Chollet, F. (2018). Deep Learning with Python (Manning).
https://github.com/hamaadshah/autoencoders_keras
https://pytorch.org
